---

- name: should have UTF-8 locales enabled
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8

- name: set timezone
  community.general.timezone:
    name: Europe/Paris

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
  notify: restart sshd

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
  notify: restart sshd