---
- name: add goaccess repository key
  ansible.builtin.apt_key:
    id: c03b48887d5e56b046715d3297bd1a0133449c3d
    keyserver: hkp://keyserver.ubuntu.com:80
    keyring: /etc/apt/trusted.gpg.d/goaccess.gpg
# alternatively: https://github.com/allinurl/goaccess/issues/2321#issuecomment-2075455648

- name: add goaccess repository
  ansible.builtin.apt_repository:
    filename: elasticsearch
    repo: deb https://deb.goaccess.io/ noble main
    state: present

- name: Install packages
  apt:
    name: python3,python3-venv,git,nginx,certbot,acl,python3-certbot-nginx,goaccess,nodejs,npm
    state: present
    update_cache: yes
