---

- name: make data directory
  become: yes
  file:
    path: "{{ app_data_dir }}"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"

- include_tasks: setup_instance.yml

- include_tasks: upgrade.yml

- include_tasks: setup_bot.yml