---

- name: create log directory
  become: yes
  file:
    path: "{{ app_logs_dir }}"
    group: 'www-data'
    owner: 'www-data'
    state: directory

- name: create src directory
  become: yes
  file:
    path: "{{ app_src_dir }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    state: directory

- name: create webroot directory
  become: yes
  file:
    path: "{{ app_webroot_dir }}"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: create goaccess directory
  become: yes
  file:
    path: "{{ app_webroot_dir }}/goaccess"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
  when: goaccess_enable