---

- name: create log directory
  become: yes
  file:
    path: "{{ app_logs_dir }}"
    group: 'root'
    owner: 'root'
    state: directory

- name: create site conf file (without SSL)
  become: yes
  template:
    src: templates/site_nossl.conf.j2
    dest: /etc/nginx/sites-available/{{ website_address }}.conf
    owner: root
    group: root
    mode: 0644
    
- name: enable website
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ website_address }}.conf
    dest: /etc/nginx/sites-enabled/{{ website_address }}.conf
    state: link

- name: restart nginx
  become: yes
  service:
    name: 'nginx'
    state: 'restarted'

- name: check address is working
  command: curl -IL "http://{{ website_address }}"
  register: result_curl
  failed_when: '"200" not in result_curl.stdout'

- name: request certificate through certbot
  become: yes
  command: certbot certonly --nginx -d {{ website_address }} --email {{ certbot_account_email }} -n --agree-tos  --force-renewal

- name: create proper site conf file (with SSL)
  become: yes
  template:
    src: templates/site.conf.j2
    dest: /etc/nginx/sites-available/{{ website_address }}.conf
    owner: root
    group: root
    mode: 0644

- name: restart nginx
  become: yes
  service:
    name: 'nginx'
    state: 'restarted'

- name: check HTTPS is working
  command: curl -IL "https://{{ website_address }}"
  register: result_curl
  failed_when: '"200" not in result_curl.stdout'
