

- name: create app directory
  file:
    path: "{{ app_dir }}"
    state: directory

- name: clone Git repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ app_src_dir }}"
    version: "{{ git_branch }}"
    depth: 1

- name: create venv and install requirements
  pip:
    requirements: "{{ app_src_dir }}/requirements.txt"
    virtualenv: "{{ app_venv_dir }}"
    virtualenv_command: "python3 -m venv"

- name: install extra requirements
  pip:
    name: gunicorn
    virtualenv: "{{ app_venv_dir }}"

- name: create webroot
  file:
    path: "{{ app_webroot_dir }}"
    state: directory

- name: link static in webroot
  become: yes
  file:
    src: "{{ website_static_path }}"
    dest: "{{ app_webroot_dir }}/static"
    state: link
  when: website_has_static

- name: Add user
  become: yes
  user:
    name: "{{ uid }}"
    group: "{{ gid }}"
    comment: app user for {{ app_name }}
    shell: /bin/bash
    password: '!'
    home: "{{ app_dir }}"

- name: Set permissions to app directory
  become: yes
  file:
    path: "{{ app_dir }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    state: directory
    recurse: yes