---

- name: check if app directory exists
  stat:
    path: "{{ app_dir }}"
  register: app_dir_exists

- include_tasks: clone_setup.yml
  when: not app_dir_exists.stat.exists

- include_tasks: update.yml
  when: app_dir_exists.stat.exists


- name: create webroot
  file:
    path: "{{ app_webroot_dir }}"
    state: directory

- name: link static in webroot
  become: yes
  file:
    src: "{{ website_static_path }}"
    dest: "{{ app_webroot_dir }}/static"
    state: link
    owner: "{{ uid }}"
    group: "{{ gid }}"
  when: website_has_static

- name: create goaccess directory
  become: yes
  file:
    path: "{{ app_webroot_dir }}/goaccess"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"