- name: Add the user
  become: yes
  user:
    name: "{{ uid }}"
    group: "{{ gid }}"
    comment: app user for {{ app_name }}
    shell: /bin/bash
    password: '!'
    home: "{{ app_dir }}"

- name: Set permissions to app directory
  become: yes
  file:
    path: "{{ app_dir }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    state: directory
    recurse: yes
